# Generated by Django 4.1.3 on 2022-11-30 14:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_staff.part', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('job_title', models.CharField(max_length=150, verbose_name='job_title')),
                ('date_start', models.DateField(verbose_name='start_date')),
                ('salary', models.PositiveIntegerField(verbose_name='salary')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='app_staff.part', verbose_name='workers')),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'workers',
            },
        ),
    ]
