# Generated by Django 4.1.3 on 2022-12-01 08:04

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_staff.part', verbose_name='parent'),
        ),
    ]
